id: P006677
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:15:22.374168
source_metadata:
  id: bdr:W00EGS1017120
  title: བོད་ལུགས་གསོ་རིག་ཚིག་མཛོད་ཆེན་མོ
  author: ''
  volumes:
    23e0c2f7330541b4ba8dec0b1baca578:
      image_group_id: I00EGS1017132
      title: ''
      volume_number: 1
      total_pages: 1276
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
